use_frameworks!

platform :ios, '13.0'

target 'VoceChat_Example' do
  pod 'VoceChat', :path => '../'
  
  pod 'SnapKit'
  pod 'SDWebImage'
  pod 'CDFInitialsAvatar'
  pod 'WoodPeckeriOS', :configurations => ['Debug']
  pod 'SwiftDate', '~> 5.0'
  
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod "RxGesture"
    
  pod 'QMUIKit', '4.6.3'
  pod 'YYKit'
  
  pod 'JCore', '3.2.3-noidfa'
  pod 'JPush', '4.8.0'

  target 'VoceChat_Tests' do
    inherit! :search_paths

    
  end
end
