use_frameworks!

platform :ios, '13.0'

target 'VoceChat_Example' do
  pod 'VoceChat', :path => '../'
  
  pod 'SnapKit'
  pod 'SDWebImage'
  pod 'CDFInitialsAvatar'
  pod 'WoodPeckeriOS', :configurations => ['Debug']
  pod 'SwiftDate', '~> 5.0'
  
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod "RxGesture"
    
  pod 'QMUIKit', '4.6.3'
  pod 'YYKit'

  target 'VoceChat_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      end
    end
  end
